### ISSUE TITLE
Broken app startup when Overriding Microsoft logs

### ISSUE THREAD

**Issue by Necriis** [serilog/serilog-aspnetcore#139] opened 2019-10-04 15:16 UTC
I have a strange behaviour when I start a new Asp .Net Core project in VS2019, with Docker support on Linux. I add the support of docker-compose, and update the default program.cs with the one in the EarlyInitializationSample. (With Serilog.AspNetCore 3.0 nuget package)
I start the app, everything works fine, it launches my browser on the WeatherForecastController (the demo controller from the Visual Studio template).

If I add a filter in the logger configuration (`.MinimumLevel.Override("System", LogEventLevel.Warning)`), it still works as expected.

BUT ! If I replace `System` by `Microsoft` (`.MinimumLevel.Override("Microsoft", LogEventLevel.Warning)`), the application start, but seems to stop loading stuff in the middle of the startup process, and it doesn't launch my browser.

My app seems to respond normally, but I fear it could hide something wierd...

**Comment by nblumhardt** [comment] 2019-10-05 09:21
Very strange! I know it's easy for me to say :-) but I think this is unlikely to be directly caused by Serilog (chances are that the odd logging behavior is a symptom of some other problem, perhaps missing assemblies in the deployment, mismatched target/runtime versions, or a broken install of something in the image.. the possibilities are pretty broad).

If you find more details or figure out how to reproduce it with a File > New Project-style app and container image, it would be great to learn more, but there's not a lot of chance we can help at this stage, sorry.

**Comment by Necriis** [comment] 2019-10-07 08:04
Yes, as I wrote in my previous post, it's very quick and straightforward to reproduce, here are the detailed steps:

- In VS2019, *Create a new project* / with *ASP.NET Core Web Application* template / clic *Create*
- In the wizard, select *API* / *No Authentication* / Uncheck *Configure for HTTPS* / Check *Enable Docker Support* for Linux / clic *Create*
- In VS, right clic on the csproj / *Add* / *Container Orchestrator Support...* / Select *Docker-Compose* / Select *Linux* / clic *OK*
- right clic on *Dependencies* / *Manage Nuget Packages* / Install *Serilog.AspNetCore* nuget package (v3.0.0)
- copy the content of [EarlyInitializationSample Program.cs](https://github.com/serilog/serilog-aspnetcore/blob/dev/samples/EarlyInitializationSample/Program.cs) into your `Program.cs`
- in Program.cs, during the LoggerConfiguration, add `.MinimumLevel.Override("System", LogEventLevel.Warning)` just after `.ReadFrom.Configuration(Configuration)`
- clic on `▶️ Docker Compose`: the app is deployed on Docker, and VS launch the browser on `http://localhost:XXXXX/weatherforecast`

Here, everything works fine.

- Now, replace `System` by `Microsoft` in `.MinimumLevel.Override("System", LogEventLevel.Warning)`
- clic on `▶️ Docker Compose`: the app is deployed on Docker, but suddently, something stop working during the initialization, VS don't launch the browser.

**Comment by Necriis** [comment] 2019-10-10 12:57
Indeed, it could just be a VS issue as it's the only *visible* problem...
But it works with .Net Core 2.2, so I'll try with the next release of .Net Core 3 !

**Comment by nblumhardt** [comment] 2019-10-12 18:44
I'll close this for now, but if you end up with more information/any data that points to an issue in Serilog, please feel free to jump back in. Thanks, Flavien!

**Closed by nblumhardt** 2019-10-12 18:44 UTC

**Comment by tbraz** [comment] 2019-11-30 01:11
> Thanks for the follow-up 👍
> 
> Just to clarify, the problem is just that VS does not launch the browser? If so, it might be that VS is waiting to see some specific (`Microsoft.*`) log output as an indication that the process is ready.

I've encountered the same issue, and after reading this thread and your comment in particular I made some testing with the logging output.

It seems indeed that VS is waiting on a specific output from Microsoft.Hosting.Lifetime to launch the browser.
```
[INF][Microsoft.Hosting.Lifetime] Now listening on: https://[::]:443
[INF][Microsoft.Hosting.Lifetime] Now listening on: http://[::]:80
[INF][Microsoft.Hosting.Lifetime] Application started. Press Ctrl+C to shut down.
```
Those are the first log outputs from that Namespace that appear in the application and if I silence them (change the log level to something higher than `Information`) the browser won't launch.

There is no issue what so ever with Serilog.

**Comment by acclaimuser** [comment] 2019-12-27 16:47
Yes. encountered this same case today when running with linux docker container. glad i found this information to confirm it. Thanks.

**Comment by dazinator** [comment] 2020-01-20 16:28
I just hit this when my application was deployed to Azure Web App for Containers. Azure starts the container, and then just waits for ages to detect whether it has started. What is the solution - can we override microsoft in general but just allow those specific entries through somehow?
