### ISSUE TITLE
.NET Core 1 Change

### ISSUE THREAD

**Issue by farzadmf** [serilog/serilog-aspnetcore#20] opened 2017-12-19 14:10 UTC
Hi,

This is not necessarily an issue, but I thought maybe I can get some insights here. We have a project that's using the old .NET Core `project.json` format. It has a custom logging library that's injected through DI, but it's not well written (!) and (I think) it even has some overrides in DI for logging interfaces.

However, as bad as this implementation of logging is, I was able to add serilog to that project, I could see logs for requests coming in , and I just needed to inject `ILogger` to my controllers and see their logs, but after upgrading that project to .NET Core 2, it seems that the whole logging pipeline is broken, and adding serilog doesn't seem to have any effect.

I know that it's impossible to know what's exactly happening without knowing the exact implementation details, but I was hoping to get some insight about logging changes between the two .NET Core versions, and what *may* be causing the issue

Thank you in advance

**Comment by nblumhardt** [comment] 2017-12-19 21:31
Hi Farzad - are you using `UseSerilog()` in the new (Core 2.0) codebase? Check out https://nblumhardt.com/2017/08/use-serilog/ for some details on the differences. Let me know if this helps.

Nick

**Comment by nblumhardt** [comment] 2017-12-19 21:37
Duplicate of https://stackoverflow.com/questions/47888929/logging-changes-between-net-core-1-project-json-and-net-core-2-regarding-ser

**Closed by nblumhardt** 2017-12-19 21:37 UTC
