### ISSUE TITLE
`UseSerilogRequestLogging` not honoring the HTTP status code? 

### ISSUE THREAD

**Issue by alexdresko** [serilog/serilog-aspnetcore#187] opened 2020-04-14 13:02 UTC
It doesn't appear as if `UseSerilogRequestLogging` honors the HTTP response code bubbled up through the pipeline. I created [this issue](https://github.com/khellang/Middleware/issues/94#issuecomment-603527112) on the khellang Problem Details middleware repo to figure out why Serilog was showing HTTP 404 errors as HTTP 500 when used in conjunction with the Problem Details middleware. KHellang's suggestion, ultimately, was that something in Serilog needs to change. Can you point a finger in the right direction, please?

**Comment by nblumhardt** [comment] 2020-04-14 22:27
Thanks for the note; this is a duplicate of https://github.com/serilog/serilog-aspnetcore/issues/185

**Closed by nblumhardt** 2020-04-14 22:27 UTC
