### ISSUE TITLE
WebHost inside Generic host not logging startup messages

### ISSUE THREAD

**Issue by gthvidsten** [serilog/serilog-aspnetcore#126] opened 2019-08-31 13:39 UTC
If you have a generic host, then inside this host you add a web host, and you are using `.UseSerilog()` for both, then the web host startup messages are not logged to Serilog.

This is what I mean by "startup messages":
> Hosting environment: Production
> Content root path: C:\Users\Me\Project\src\App\bin\Debug\netcoreapp3.0
> Now listening on: http://localhost:5000
> Application started. Press Ctrl+C to shut down.

**Program.cs**
```csharp
public static async Task Main(string[] args)
{
    Log.Logger = new LoggerConfiguration()
        .MinimumLevel.Debug()
        .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
        .Enrich.FromLogContext()
        .WriteTo.Console()
        .CreateLogger();

    IHostBuilder builder = new HostBuilder()
        .UseSerilog()
        .ConfigureServices(services => { collection.AddHostedService<MyService>(); });

    await builder.RunConsoleAsync();
}
```
**MyService.cs**
```csharp
public class MyService : IHostedService
{
    private IWebHost _webHost;

    public async Task StartAsync(CancellationToken ct)
    {
        _webHost = WebHost.CreateDefaultBuilder()
            .UseStartup<MyService>()
            .UseSerilog()
            .Build();

        _webHost.RunAsync();
    }

    public async Task StopAsync(CancellationToken ct)
    {
        await _webHost.StopAsync();
    }

    public void ConfigureServices(IServiceCollection services) {
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env) {
    }
}
```
When this starts the logging from the generic host uses Serilog, but the logging in the web host startup does not. Logging of requests to the web host, on the other hand, does use Serilog. This is apparent in the output:

> Hosting environment: Production
> Content root path: C:\Users\Me\Project\src\App\bin\Debug\netcoreapp3.0
> Now listening on: http://localhost:5000
> Application started. Press Ctrl+C to shut down.
> [15:32:01 INF] Application started. Press Ctrl+C to shut down.
> [15:32:01 INF] Hosting environment: Production
> [15:32:01 INF] Content root path: C:\Users\Me\Project\src\App\bin\Debug\netcoreapp3.0\
> [15:32:33 INF] Request starting HTTP/1.1 GET http://localhost:5000/
> [15:32:33 INF] Request finished in 13.2002ms 404

**Expected behaviour**

The startup messages from a web host inside a generic host should still be logged to Serilog.

**Comment by nblumhardt** [comment] 2019-09-01 22:17
Hi @gthvidsten - In this case, it should only be necessary to add `UseSerilog` to the `HostBuilder` and not to the web host configuration. Let me know if this helps~! Nick

**Comment by gthvidsten** [comment] 2019-09-02 07:46
If I don't add `UseSerilog` to the web host configuration, then nothing from the web host is logged to Serilog.
If I remove `.UseSerilog()` from `_webHost = WebHost.CreateDefaultBuilder()` the output looks like this:

> Hosting environment: Production
> Content root path: C:\Users\Me\Project\src\App\bin\Debug\netcoreapp3.0
> Now listening on: http://localhost:5000
> Application started. Press Ctrl+C to shut down.
> [09:42:12 INF] Application started. Press Ctrl+C to shut down.
> [09:42:12 INF] Hosting environment: Production
> [09:42:12 INF] Content root path: C:\Users\Me\Project\src\App\bin\Debug\netcoreapp3.0\
> info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
>       Request starting HTTP/1.1 GET http://localhost:5000/
> info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
>       Request finished in 33.3207ms 404

**Comment by nblumhardt** [comment] 2019-09-02 23:05
Interesting - thanks for the follow-up.

I've only personally used the web host integration in .NET Core 2.x, and the new hosting implementation in .NET Core 3, so I may have missed some combination of these two in 2.x projects that causes trouble...

Are you using .NET Core 2.2?

(There are a pair of examples in the registry that "work" for me, https://github.com/serilog/serilog-aspnetcore/tree/dev/samples is currently 2.2, and https://github.com/serilog/serilog-aspnetcore/tree/updated-examples/samples is the un-merged 3.0 versions.)

**Comment by nblumhardt** [comment] 2019-09-02 23:06
...and I just answered my own question reading your: `C:\Users\Me\Project\src\App\bin\Debug\netcoreapp3.0` ... hmm. Okay, I'll take a closer look at the 3.0 updates. Might be worth checking where the updated samples and your app differ.

**Comment by nblumhardt** [comment] 2019-09-10 20:18
Hi @gthvidsten  - rather than `new HostBuilder()`, have you tried the `Host.CreateDefaultBuilder()` method? Its one conspicuous difference between your example code above, and the apps I've been working on.

**Comment by gthvidsten** [comment] 2019-09-10 21:19
@nblumhardt I just tried changing the initial host in Program.cs from `new HostBuilder()` to `Host.CreateDefaultBuilder()` but there was unfortunately no change.

**Comment by sungam3r** [comment] 2019-09-10 22:46
`Host` and `WebHost` are completely different hosts.

**Comment by nblumhardt** [comment] 2019-09-11 04:37
Thanks @sungam3r - yes, we've been discussing the relative behavior of each of them earlier in this thread :-)

**Comment by nblumhardt** [comment] 2019-09-11 04:38
@gthvidsten another thought, are you using preview8 or later?

**Comment by gthvidsten** [comment] 2019-09-11 09:08
@nblumhardt Yes, I'm on preview8

**Comment by nblumhardt** [comment] 2019-09-11 09:15
Odd! I'm running preview 8, with `UseSerilog()` called on the `HostBuilder` only (not the web host builder) and everything works; maybe `UseSerilog()` needs to be called earlier than something else you're invoking on the `HostBuilder`? Its called very early in our app:

```csharp
        return Host.CreateDefaultBuilder()
            .UseServiceProviderFactory(new AutofacServiceProviderFactory())
            .UseSerilog()
            // etc.
```

**Comment by gthvidsten** [comment] 2019-09-11 10:19
It's called as early as possible, as you can see in `Program.cs` in the original post. I tried calling `.UseSerilog()` before `.UseStartup<MyService>()` in `MyService.cs`, but that had no effect.
If I don't use Serilog on the `WebHost` I'm back to nothing logged through Serilog from the webhost ([as described here](https://github.com/serilog/serilog-aspnetcore/issues/126#issuecomment-527040684))

**Comment by sungam3r** [comment] 2019-09-11 11:32
I just realized that I have long known what the problem is. I did not carefully read the original post. you Just need to look into the source code. Look, everything is simple: https://github.com/aspnet/Extensions/commit/c2351bb4664c89ef40004989d2c58988ffb79445

![image](https://user-images.githubusercontent.com/21261007/64693806-cff05200-d4a0-11e9-87fe-fac27fbe0e3c.png)
![image](https://user-images.githubusercontent.com/21261007/64693827-ded70480-d4a0-11e9-8d77-6ef1aef47b65.png)

**Comment by gthvidsten** [comment] 2019-09-11 11:51
@sungam3r They removed Console output and use the Logger instead. As far as I can see, this does not explain why a `WebHost` logs its startup to the console when the webhost is started from within a generic host.

**Closed** 2019-09-11 20:43 UTC

**Comment by gmarokov** [comment] 2020-08-07 11:21
> @sungam3r Good find! So it seems this is an issue with ASP,NET Core outputting messages to the console regardless of logging, which basically explains everything.
> It also means this is not a Serilog issue at all, so I'll close this issue and see if anybody has reported this for aspnet/AspNetCore (and report it myself if not).
> 
> Thanks for the assistance!

Hey @gthvidsten I have the same issue in 2.1. Did you raised issue or found a working solution? Regards :)
