### ISSUE TITLE
how to use with EF Core

### ISSUE THREAD

**Issue by papiermache** [serilog/serilog-aspnetcore#45] opened 2018-04-18 15:27 UTC
.. which is expecting to work with an ILoggerFactory, which is not being used by this pkg?

**Comment by andymac4182** [comment] 2018-04-18 20:55
Do you have an example of what you are trying to do that doesn't work?

**Comment by papiermache** [comment] 2018-04-19 00:11
Hi Andrew,
I am using serilog in a Core 2.0 (console) app. Would like to log Ef generated sql stmts. EF doc says it works with .NET Core’s ILoggerFactory. But I’ve implemented the alternative Serilog format suggestion and as far as I know there is no IloggerFactory:


            // Add Serilog specifically (and not generic .net code ILoggerFactory) ..
            // https://nblumhardt.com/2017/08/use-serilog/

            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .Enrich.FromLogContext()
                //.WriteTo.Console()
                //.WriteTo.File("d:\\logs\\myapp.txt", rollingInterval: RollingInterval.Day)
                .CreateLogger();

            serviceCollection.AddSingleton<ILogger>(Log.Logger);

So given this, how do I bolt this logging onto EF?
Regards, Rick.

**Comment by andymac4182** [comment] 2018-04-19 05:57
I think you are looking for Serilog.Extensions.Logging https://github.com/serilog/serilog-extensions-logging that integrates with MEL.

What you have registered is just the Serilog ILogger in the container Serilog.Extensions.Logging adds that to the Microsoft logging abstraction.

**Comment by nblumhardt** [comment] 2018-04-19 06:53
:+1: _Serilog.AspNetCore_'s `UseSerilog()` will set everything up that you need, here, including the `ILoggerFactory.

**Comment by danjohnso** [comment] 2018-04-20 22:05
I'm actually having issues with EF Core too right now.  I'm using _UseSerilog()_ and I am getting logs from my stuff and from kesterel, but nothing from entity framework even with the minimum level set to Verbose.  I thought I just needed to call services.AddDbContext() and it would take care of adding the LoggerFactory that was need.  Something else I am forgetting?

**Comment by danjohnso** [comment] 2018-04-22 00:59
I tried in config and in code with this configuration, also tried using a console and file debugger to see if the sink made a difference.  

`
	"Serilog": {
		"MinimumLevel": {
			"Default": "Verbose",
			"Override": {
				"Microsoft": "Verbose",
				"System": "Verbose"
			}
		},
		"Enrich": [ "FromLogContext", "WithMachineName", "WithEnvironmentUserName", "WithExceptionData" ],
		"WriteTo": [
			{
				"Name": "Seq",
				"Args": { "serverUrl": "http://localhost:5341" }
			}
		]
	}`

Here is my Program.cs too:
```

public static IConfiguration Configuration { get; } = new ConfigurationBuilder()
	.SetBasePath(Directory.GetCurrentDirectory())
	.AddJsonFile("appsettings.json", false, true)
	.AddJsonFile($"appsettings.{Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT")}.json", false, true)
	.AddEnvironmentVariables()
	.Build();

public static int Main(string[] args)
{
	string logPath = Path.Combine(Directory.GetCurrentDirectory(), "logs");
	if (!Directory.Exists(logPath))
	{
		Directory.CreateDirectory(logPath);
	}

	if (Configuration.GetValue<bool>("ApplicationSettings:EnableSelfLog"))
	{
		SelfLog.Enable(TextWriter.Synchronized(File.CreateText(Path.Combine(logPath, "internal.txt"))));
	}

	Log.Logger = new LoggerConfiguration()
				 .MinimumLevel.Verbose()
				 .WriteTo.Seq("http://localhost:5341")
				 //.ReadFrom.Configuration(Configuration)
				 .Destructure.UsingAttributes()
				 .CreateLogger();

	try
	{
		Log.Information("Starting web host");

		BuildWebHost(args).Run();

		MigrateDatabases();

		return 0;
	}
	catch (Exception ex)
	{
		Log.Fatal(ex, "Host terminated unexpectedly");
		return 1;
	}
	finally
	{
		Log.CloseAndFlush();
	}
}

public static IWebHost BuildWebHost(string[] args) =>
	new WebHostBuilder()
		.UseKestrel()
		.UseContentRoot(Directory.GetCurrentDirectory())
		.UseAutofacMultitenantRequestServices(() => Startup.ApplicationContainer)
		.UseIISIntegration()
		.UseStartup<Startup>()
		.UseConfiguration(Configuration)
		.UseSerilog()
		.Build();
```

Package versions:

```
<PackageReference Include="Autofac.AspNetCore.Multitenant" Version="1.0.0" />
<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="4.2.2" />
<PackageReference Include="IdentityModel" Version="3.6.1" />
<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.7" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.2" />
<PackageReference Include="Serilog" Version="2.6.0" />
<PackageReference Include="Serilog.AspNetCore" Version="2.0.0" />
<PackageReference Include="Serilog.Enrichers.Environment" Version="2.1.2" />
<PackageReference Include="Serilog.Settings.Configuration" Version="2.6.1" />
<PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
<PackageReference Include="Serilog.Sinks.File" Version="4.0.0" />
<PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.0" />
<PackageReference Include="Serilog.Sinks.Seq" Version="4.0.0" />
<PackageReference Include="Destructurama.Attributed" Version="1.2.0" />
```

**Comment by nblumhardt** [comment] 2018-04-23 22:03
Thanks @danjohnso - I'll take a look as soon as I have an opportunity.

All - any help digging into this would be appreciated :-)

**Comment by adamchester** [comment] 2018-04-24 02:40
Hey @danjohnso, I've confirmed here that `UseSerilog()` still works.

I took a quick look at your code above, and I couldn't spot anything obviously wrong, except that your `MigrateDatabases();` call is *after* the `BuildWebHost(args).Run();` statement. Are you expecting to see the logs generated by `MigrateDatabases`? 

If that's not the issue, perhaps you could publish a full sample application that we can easily compile and run?

**Comment by danjohnso** [comment] 2018-04-24 14:39
Not by migrate databases, trying to see actual queries.  I will try to put together a simple app for running

**Comment by danjohnso** [comment] 2018-04-24 16:31
Threw together striped down example here: [Repo](https://github.com/danjohnso/testapp)
Maybe related to my issue [here](https://stackoverflow.com/questions/49950032/autofac-multitenant-database-configuration) with the multi-tenant registrations of the dbcontexts?

**Comment by adamchester** [comment] 2018-04-25 01:30
I had a quick look at your [testapp](https://github.com/danjohnso/testapp), @danjohnso.

I noticed, at the time you [build the `AutoFac.IContainer`](https://github.com/danjohnso/testapp/blob/363651c2d978e52afe44bd81c51eea7d1b54ab11/TestApp/Startup.cs#L60-L78), the [`SerilogLoggerFactory` hasn't yet been registered](https://github.com/serilog/serilog-aspnetcore/blob/7c9174937cac13c28799a38b03fc4b5b2898afc1/src/Serilog.AspNetCore/SerilogWebHostBuilderExtensions.cs#L41), which means that the default ASPNET Core logging would still be the registered provider.

I can't say for sure at this stage, but this doesn't appear to be a problem with Serilog. It appears to be caused by how you're registering and resolving your container services @danjohnso.

**Comment by danjohnso** [comment] 2018-04-25 15:07
@adamchester you are right, I dont see the logger factory from serilog registered by the time I build my container in ConfigureServices, but how do I get that to happen?  I thought UseSerilog was the way to register the logger in .NET Core 2.

**Comment by adamchester** [comment] 2018-04-25 22:49
Sorry, I might have been mistaken. I tried again just now, and it seems your Autofac container *does* end up with Serilog being the configured logger factory.

In that case, I guess it must be something related to how EF finds the configured logger factory; it must be looking for it at the wrong time, or in the wrong place (container instance). Sorry I don't have any further insights yet.

**Comment by skomis-mm** [comment] 2018-04-26 18:09
Try to "fix" like this:
1. add `DbContextOptions<>` to the constructor and pass it to the base type:
```csharp
public class TenantTwoContext : BaseContext
    {
	    public TenantTwoContext(AppTenant tenant, DbContextOptions<TenantTwoContext> options) 
		    : base(tenant, options)
	    {
	    }

```
so that you can make use of another overload for `AddDbContext` which accepts and action:
2. make adjustments to `DbContext` registration:
```csharp
tenantServices.AddDbContext<TenantTwoContext>((sp, options) => options.UseLoggerFactory(container.Resolve<ILoggerFactory>()));
```

**Comment by nblumhardt** [comment] 2019-05-22 09:07
Sounds like `UseLoggerFactory()` is the way to go, here. I'd guess by the comment that EF is otherwise making assumptions about the internals of the default provider? 🤷‍♂ - let us know if you hit negative impact, @danjohnso 👍

**Closed by nblumhardt** 2019-05-22 09:07 UTC

**Comment by danjohnso** [comment] 2019-05-22 18:08
Been using without any noticeable impact, though I probably don't have the load some people do to notice.

**Comment by TheMagnificent11** [comment] 2020-01-18 05:06
What was the solution here?  I assume it is `UseLoggerFactory` when configuring the EF Core DB service.  However, I'm not sure how best to resolve the `ILoggerFactory`.

I've got an ASP.Net Core 3.1 app that's using Autofac and Serilog.  In my `Startup` I migrate the DB using the following code.

```
 private static void MigrateDatabase(IApplicationBuilder app)
        {
            using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                var context = serviceScope.ServiceProvider.GetService<DatabaseContext>();
                context.Database.Migrate();
            }
        }
```

However, in my console, I get a mix of Serilog and standard MS logging.

```
[14:54:57 DBG] Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT 1
[14:54:57 INF] Executed DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT 1
[14:54:57 DBG] Closing connection to database 'MySampleApp' on server '.'.
[14:54:57 DBG] Closed connection to database 'MySampleApp' on server '.'.
[14:54:57 DBG] Creating DbCommand for 'ExecuteScalar'.
[14:54:57 DBG] Created DbCommand for 'ExecuteScalar' (8ms).
[14:54:57 DBG] Opening connection to database 'MySampleApp' on server '.'.
[14:54:57 DBG] Opened connection to database 'MySampleApp' on server '.'.
[14:54:57 DBG] Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
[14:54:57 INF] Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
[14:54:57 DBG] Closing connection to database 'MySampleApp' on server '.'.
```

Here's how I configured the logging.  I'm not sure how to resolve the `ILoggerFactory` when using `UseLoggerFactory` in the `AddDbContextPool` service configuration.

```
        public static void ConfigureContainer(ContainerBuilder builder)
        {
            builder.RegisterLogger(); // using AutofacSerilogIntegration
        }

        public void ConfigureServices(IServiceCollection services)
        {
            var levelSwitch = new LoggingLevelSwitch
            {
                MinimumLevel = LogEventLevel.Debug
            };

            var config = new LoggerConfiguration()
                .ReadFrom.Configuration(this.Configuration)
                .MinimumLevel.ControlledBy(levelSwitch)
                .WriteTo.Console()
                .Enrich.FromLogContext();

            Log.Logger = config.CreateLogger();

            services.AddLogging(builder => builder.AddSerilog(dispose: true));

            services.AddDbContextPool<DatabaseContext>(options =>
            {
                options.UseSqlServer(this.Configuration.GetConnectionString("DefaultConnection"));

                // How should I resolve ILoggerFactory?
                options.UseLoggerFactory();
            });
        }
```

**Comment by nblumhardt** [comment] 2020-01-20 06:36
@TheMagnificent11 check out #160 - possible solution in there, still needs some time/research from someone using EF Core. Cheers!

**Comment by TheMagnificent11** [comment] 2020-01-24 13:17
Thanks @nblumhardt. I got it working by doing what you suggested by configuring the logging in my `Program` class using the following (and leaving the rest of my implementation that same...except removing the `UseLoggerFactory` from my `DbContext` configuration).

```
using System.IO;
using Autofac.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Serilog;

namespace SampleApiWebApp
{
    public static class Program
    {
        public static void Main(string[] args)
        {
            var host = Host.CreateDefaultBuilder(args)
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    logging.AddSerilog();
                })
                .UseServiceProviderFactory(new AutofacServiceProviderFactory())
                .ConfigureWebHostDefaults(webHostBuilder =>
                {
                    webHostBuilder
                        .UseContentRoot(Directory.GetCurrentDirectory())
                        .UseStartup<Startup>();
                })
                .Build();

            host.Run();
        }
    }
}

```
