### ISSUE TITLE
RequestId performance is inconsistent

### ISSUE THREAD

**Issue by SpringHgui** [serilog/serilog-aspnetcore#296] opened 2022-05-12 05:54 UTC
```
Serilog.AspNetCore 6.0.0-dev-00265
Serilog 2.11.0
```

temp：`[{Timestamp:HH:mm:ss} {RequestId} {Level:u3}] {Message:lj}{NewLine}{Exception}`

## My situation：
RequestId performance is inconsistent

***Local environment***：RequestId performance like `0HMHJP0IGCO99:00000002`
***Production environment***：RequestId performance like `80000cca-0000-d600-b63f-84710c7967bb`

**Comment by nblumhardt** [comment] 2022-05-12 05:57
Hi again; by:

> The request id doesn't come from this package (or from Serilog at all), it's set by the ASP.NET Core hosting infrastructure.

I meant Microsoft/.NET's ASP.NET Core infrastructure, which is maintained in https://github.com/microsoft/aspnetcore

Hope this helps; closing again as it's not part of the Serilog project.

Duplicate of https://github.com/serilog/serilog/issues/1677

**Closed by nblumhardt** 2022-05-12 05:57 UTC
Labels: bug
